"""轻量级界面本地化支持。"""

from PyQt6.QtCore import QSettings, QObject, pyqtSignal


TRANSLATIONS = {
    "zh_CN": {
        "language_name": "中文",
        "brand_subtitle": "让每一次离开，都有一个明确的时间",
        "window_title": "电源定时工具",
        "tab_shutdown": "定时关机",
        "tab_sleep": "定时睡眠",
        "next_action": "下一步操作",
        "ready": "待机",
        "status_ready": "就绪",
        "running": "运行中",
        "execution_time": "执行时间",
        "execution_caption": "倒计时结束后执行当前选中的操作",
        "one_minute": "1 分钟",
        "twenty_four_hours": "24 小时",
        "duration_minutes": "{value}分钟",
        "minutes_suffix": " 分钟",
        "never": "永不",
        "duration_hours": "{hours}小时",
        "duration_hours_minutes": "{hours}小时{minutes}分",
        "preview_shutdown": "预计关机时间: {time}",
        "preview_screen": "预计关屏时间: {time}",
        "preview_both": "预计关屏: {screen_time}  睡眠: {sleep_time}",
        "preview_sleep": "预计睡眠时间: {time}",
        "options": "操作选项",
        "phase_wait": "等待",
        "phase_lock": "锁屏",
        "phase_screen": "关屏",
        "phase_sleep": "睡眠",
        "phase_shutdown": "关机",
        "shutdown_summary": "关机",
        "sleep_summary": "睡眠与关屏",
        "sleep_mode": "系统睡眠",
        "screen_mode": "关闭屏幕",
        "both_mode": "关屏后睡眠",
        "shutdown_hint": "倒计时结束后系统将自动关机。首次使用可能需要输入管理员密码。",
        "screen_mode_tip": "仅关闭显示器，电脑保持运行",
        "both_mode_tip": "先关闭显示器，等待后再进入睡眠",
        "offset_label": "提前关屏",
        "offset_suffix": "后睡眠",
        "lock_screen": "操作前锁定屏幕",
        "prevent_sleep": "倒计时防睡眠",
        "prevent_sleep_tip": "倒计时期间阻止系统自动睡眠",
        "idle_title": "系统空闲睡眠",
        "idle_hint": "永久生效，0 = 永不。保存时需要输入管理员密码。",
        "idle_hint_windows": "显示当前电源计划的接通电源值，保存时同步修改接通电源与电池供电设置。0 = 永不。",
        "display_sleep": "关屏",
        "system_sleep": "睡眠",
        "save_settings": "保存设置",
        "start": "▶  开始倒计时",
        "stop": "⏹  停止运行",
        "help": "帮助",
        "help_tip": "查看使用说明和权限提示",
        "tray_toggle": "显示/隐藏",
        "tray_quit": "退出",
        "help_title": "帮助",
        "help_permissions": "权限提示：\n• macOS 关机和系统空闲设置可能需要管理员密码。\n• 锁屏操作需要允许应用控制“系统事件”。\n• 关闭窗口后任务会继续在菜单栏托盘运行。",
        "shutdown_info": "1. 拖动滑块设置关机倒计时\n2. 点击「开始倒计时」，结束时系统自动关机\n3. 「停止运行」可取消关机计划\n4. 关闭窗口将最小化到托盘继续运行",
        "sleep_info": "1. 选择模式并拖动滑块设置倒计时\n2. 点击「开始倒计时」启动任务\n3. 「停止运行」可取消任务\n4. 「系统空闲睡眠」可永久修改系统电源参数",
        "shutdown_authorizing": "正在创建关机计划，请完成系统授权…",
        "shutdown_scheduled": "将在 {time} 关机",
        "scheduled_action": "将在 {time} {action}",
        "shutdown_executed": "系统关机已执行",
        "shutdown_create_failed": "无法创建关机计划，请检查授权",
        "shutdown_canceling": "正在取消关机计划…",
        "shutdown_wait_cancel": "正在等待并取消关机计划…",
        "shutdown_canceled": "关机任务已取消",
        "shutdown_cancel_failed": "取消关机计划失败，请重试",
        "sleep_starting": "正在进入睡眠…",
        "screen_starting": "正在关闭屏幕…",
        "both_waiting": "正在等待关屏命令完成…",
        "both_starting": "正在执行关屏和睡眠…",
        "power_command_sent": "系统睡眠命令已发送",
        "screen_off": "屏幕已关闭",
        "both_command_sent": "关屏和睡眠命令已发送",
        "sleep_failed": "进入睡眠失败，请检查系统权限",
        "screen_failed": "关闭屏幕失败，请检查系统权限",
        "both_failed": "关屏或睡眠失败，请检查系统权限",
        "power_failed": "电源操作失败，请检查系统权限",
        "task_canceled": "任务已取消",
        "idle_updated": "系统空闲睡眠设置已更新",
        "idle_saved": "已保存",
        "idle_save": "保存设置",
        "idle_save_failed": "保存失败",
        "idle_saving": "保存中…",
        "idle_error": "系统设置保存失败，请重试",
    },
    "en_US": {
        "language_name": "English",
        "brand_subtitle": "A clear time for every time you step away",
        "window_title": "Power Timer",
        "tab_shutdown": "Schedule Shutdown",
        "tab_sleep": "Schedule Sleep",
        "next_action": "NEXT ACTION",
        "ready": "Ready",
        "status_ready": "Ready",
        "running": "Running",
        "execution_time": "Execution time",
        "execution_caption": "The selected action runs when the countdown ends",
        "one_minute": "1 min",
        "twenty_four_hours": "24 hours",
        "duration_minutes": "{value} min",
        "minutes_suffix": " min",
        "never": "Never",
        "duration_hours": "{hours} hr",
        "duration_hours_minutes": "{hours} hr {minutes} min",
        "preview_shutdown": "Shutdown at {time}",
        "preview_screen": "Display off at {time}",
        "preview_both": "Display off: {screen_time}  Sleep: {sleep_time}",
        "preview_sleep": "Sleep at {time}",
        "options": "Action options",
        "phase_wait": "Waiting",
        "phase_lock": "Lock",
        "phase_screen": "Display",
        "phase_sleep": "Sleep",
        "phase_shutdown": "Shutdown",
        "shutdown_summary": "Shutdown",
        "sleep_summary": "Sleep & display",
        "sleep_mode": "System sleep",
        "screen_mode": "Turn off display",
        "both_mode": "Display, then sleep",
        "shutdown_hint": "The system will shut down when the countdown ends. Administrator permission may be required.",
        "screen_mode_tip": "Turn off the display while keeping the computer running",
        "both_mode_tip": "Turn off the display, then enter sleep",
        "offset_label": "Turn off display",
        "offset_suffix": "before sleep",
        "lock_screen": "Lock before action",
        "prevent_sleep": "Prevent auto-sleep",
        "prevent_sleep_tip": "Prevent system sleep while the countdown is running",
        "idle_title": "System idle sleep",
        "idle_hint": "Permanent setting. 0 = Never. Administrator permission is required to save.",
        "idle_hint_windows": "Shows the plugged-in value for the active power plan and synchronizes plugged-in and battery settings when saved. 0 = Never.",
        "display_sleep": "Display",
        "system_sleep": "Sleep",
        "save_settings": "Save settings",
        "start": "▶  Start countdown",
        "stop": "⏹  Stop task",
        "help": "Help",
        "help_tip": "View usage and permission guidance",
        "tray_toggle": "Show / Hide",
        "tray_quit": "Quit",
        "help_title": "Topos Power Help",
        "help_permissions": "Permissions:\n• macOS shutdown and idle settings may require an administrator password.\n• Screen locking requires permission to control System Events.\n• Closing the window keeps the task running in the menu bar.",
        "shutdown_info": "1. Drag the slider to set the shutdown countdown\n2. Click “Start countdown” to schedule shutdown\n3. “Stop task” cancels the shutdown schedule\n4. Closing the window keeps the task in the tray",
        "sleep_info": "1. Choose a mode and set the countdown\n2. Click “Start countdown” to begin\n3. “Stop task” cancels the task\n4. “System idle sleep” changes the permanent power settings",
        "shutdown_authorizing": "Creating shutdown schedule. Complete the system authorization…",
        "shutdown_scheduled": "Shutdown scheduled for {time}",
        "scheduled_action": "{action} at {time}",
        "shutdown_executed": "System shutdown executed",
        "shutdown_create_failed": "Could not create the shutdown schedule. Check authorization.",
        "shutdown_canceling": "Cancelling shutdown schedule…",
        "shutdown_wait_cancel": "Waiting to cancel shutdown schedule…",
        "shutdown_canceled": "Shutdown task cancelled",
        "shutdown_cancel_failed": "Could not cancel shutdown schedule. Try again.",
        "sleep_starting": "Entering sleep…",
        "screen_starting": "Turning off display…",
        "both_waiting": "Waiting for the display command to finish…",
        "both_starting": "Turning off display and entering sleep…",
        "power_command_sent": "Sleep command sent",
        "screen_off": "Display turned off",
        "both_command_sent": "Display and sleep commands sent",
        "sleep_failed": "Could not enter sleep. Check system permissions.",
        "screen_failed": "Could not turn off the display. Check system permissions.",
        "both_failed": "Display or sleep failed. Check system permissions.",
        "power_failed": "Power action failed. Check system permissions.",
        "task_canceled": "Task cancelled",
        "idle_updated": "System idle sleep settings updated",
        "idle_saved": "Saved",
        "idle_save": "Save settings",
        "idle_save_failed": "Save failed",
        "idle_saving": "Saving…",
        "idle_error": "Could not save system settings. Try again.",
    },
}

LANGUAGE_OPTIONS = (("zh_CN", "中文"), ("en_US", "English"))


class LanguageManager(QObject):
    """管理当前语言，并记住用户上次选择。"""

    language_changed = pyqtSignal(str)
    languages = LANGUAGE_OPTIONS

    def __init__(self, parent=None):
        super().__init__(parent)
        settings = QSettings("Topos", "ToposPower")
        saved = settings.value("language", "zh_CN")
        self.language = saved if saved in TRANSLATIONS else "zh_CN"

    def set_language(self, language):
        if language not in TRANSLATIONS or language == self.language:
            return
        self.language = language
        QSettings("Topos", "ToposPower").setValue("language", language)
        self.language_changed.emit(language)

    def text(self, key, **values):
        value = TRANSLATIONS[self.language].get(key, key)
        return value.format(**values) if values else value
